volumes:
  pitchern-config-server-data:

services:
  pitchern-config-server:
    container_name: pitchern-config-server-container
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - pitchern-config-server-data:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
